### ISSUE TITLE
Download csv spreadsheet summarizing detections per hour and day

### ISSUE THREAD

**Issue by xaviermouy** [xaviermouy/SoundScope#14]
Soundscope needs to have the ability for the user to download a csv spreadsheet summarizing the number of detections for a given time frame. 

SoundScope is already creating these summary tables for the hourly and daily visualization tabs. So, implementing this would consist of dowloading the daily and hourly pandas dataframes. 

The csv spreadsheet needs to include the following metadata:
- date of creation of the csv file
- confidence threshold used
- class label used (i.e. species/call type code)
- name of user who generated the csv file
- time zone (relative to UTC)

The csv file needs to have at least the follwoing columns:
- Date in ISO 8601 compliant date/time format:  YYYYMMDDTHHMMSS 
- Number of detections

**Comment by xaviermouy** [comment]
@namariD and Genevieve, you mentioned that the csv file should be compatible with other tools and databases like Makara and PACM. Could you please indicate what other columns you need in the csv file and in what format ?

**Comment by xaviermouy** [comment]
After discussion with Annamaria dn Gen, the csv file should also include the following:

- Date/time relative to the time zone of the recordings
- Date/Time  relative to the analysis time zone (to be defined by the user when loading data to SoundScope)

Header should include:
- Time zone of the recordings (i.e. UTC+ hour offset)
- Time zone of the analysis (i.e. UTC+ hour offset)
- version of SoundScope used

**Comment by xaviermouy** [comment]
From Gen:

It would be helpful having the following columns:
-start date/time
-end date/time
-number of detections
-"Manual_Review"
-"Comments"

Exemple of spreadsheet currently used:
[NAVFAC_NC_201710_HAT03B_RIWH_DAILY_GMT_MM.csv](https://github.com/user-attachments/files/16716668/NAVFAC_NC_201710_HAT03B_RIWH_DAILY_GMT_MM.csv)

**Comment by namariD** [comment]
Here is an example dolphin spreadsheet. The columns listed by Gen work well for us as well.
[NEFSC_MA-RI_202011_COX01_dolphins_hourly.xlsx](https://github.com/user-attachments/files/16730566/NEFSC_MA-RI_202011_COX01_dolphins_hourly.xlsx)

All odontocete analysis is done in the timezone of the soundfiles and is hourly presence so we can adapt to whatever timezone is needed

**Comment by namariD** [comment]
In October, we will revisit this to have a template based on what the postgres database needs

**Comment by xaviermouy** [comment]
Resolved in version 20241202

**Comment by xaviermouy** [comment]
CSV button added to v20241202 to download daily and hourly detection summaries as csv files
